"""
Standard Signal Model for Deriv Crypto AI Bot Stage 4.

Provides standardized representation of candidate signals generated by independent
crypto strategy agents.
"""

from dataclasses import dataclass, field
from enum import Enum
import time
import uuid
from typing import Dict, Any, Optional


class SignalDirection(str, Enum):
    BULLISH = "BULLISH"
    BEARISH = "BEARISH"
    NEUTRAL = "NEUTRAL"
    ABSTAIN = "ABSTAIN"


class SignalStatus(str, Enum):
    CANDIDATE = "CANDIDATE"
    REJECTED = "REJECTED"
    ABSTAINED = "ABSTAINED"


class SignalTier(str, Enum):
    A = "A"          # High quality candidate
    B = "B"          # Moderate candidate
    C = "C"          # Weak candidate
    REJECT = "REJECT" # Insufficient evidence/quality


class RejectionReason(str, Enum):
    DATA_NOT_READY = "DATA_NOT_READY"
    STALE_DATA = "STALE_DATA"
    HISTORY_ONLY = "HISTORY_ONLY"
    LOW_DATA_QUALITY = "LOW_DATA_QUALITY"
    REGIME_NOT_READY = "REGIME_NOT_READY"
    REGIME_MISMATCH = "REGIME_MISMATCH"
    LOW_MARKET_QUALITY = "LOW_MARKET_QUALITY"
    TIMEFRAME_CONFLICT = "TIMEFRAME_CONFLICT"
    WEAK_TREND = "WEAK_TREND"
    WEAK_MOMENTUM = "WEAK_MOMENTUM"
    NO_BREAKOUT = "NO_BREAKOUT"
    NO_RANGE = "NO_RANGE"
    STRUCTURE_UNCLEAR = "STRUCTURE_UNCLEAR"
    LOW_CONFIDENCE = "LOW_CONFIDENCE"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"
    EXPIRED = "EXPIRED"
    COOLDOWN_ACTIVE = "COOLDOWN_ACTIVE"
    STRATEGY_EXCEPTION = "STRATEGY_EXCEPTION"


@dataclass
class StrategySignal:
    """
    Standardized Strategy Signal object produced by crypto strategy agents.
    
    IMPORTANT: confidence measures STRATEGY SIGNAL CONFIDENCE (setup strength),
    NOT win probability.
    """
    signal_id: str
    symbol: str
    strategy: str
    timestamp: float
    timeframe: str
    direction: SignalDirection
    confidence: float                          # 0.00 - 1.00 setup strength
    regime: str
    regime_confidence: float
    market_quality: float
    timeframe_alignment: float
    entry_context: Dict[str, Any] = field(default_factory=dict)
    invalidation_context: Dict[str, Any] = field(default_factory=dict)
    supporting_evidence: Dict[str, float] = field(default_factory=dict)
    conflicting_evidence: Dict[str, float] = field(default_factory=dict)
    feature_snapshot_timestamp: float = 0.0
    data_quality: float = 1.0
    status: SignalStatus = SignalStatus.ABSTAINED
    rejection_reason: Optional[RejectionReason] = None
    tier: SignalTier = SignalTier.REJECT
    created_at: float = field(default_factory=time.time)
    expires_at: Optional[float] = None
    source_candle_timestamp: Optional[float] = None

    def is_candidate(self) -> bool:
        return self.status == SignalStatus.CANDIDATE

    def is_expired(self, current_time: Optional[float] = None) -> bool:
        if self.expires_at is None:
            return False
        now = time.time() if current_time is None else current_time
        return now >= self.expires_at

    def to_dict(self) -> Dict[str, Any]:
        return {
            "signal_id": self.signal_id,
            "symbol": self.symbol,
            "strategy": self.strategy,
            "timestamp": self.timestamp,
            "timeframe": self.timeframe,
            "direction": self.direction.value if isinstance(self.direction, Enum) else str(self.direction),
            "confidence": round(self.confidence, 4),
            "regime": self.regime,
            "regime_confidence": round(self.regime_confidence, 4),
            "market_quality": round(self.market_quality, 4),
            "timeframe_alignment": round(self.timeframe_alignment, 4),
            "entry_context": self.entry_context,
            "invalidation_context": self.invalidation_context,
            "supporting_evidence": {k: round(v, 4) for k, v in self.supporting_evidence.items()},
            "conflicting_evidence": {k: round(v, 4) for k, v in self.conflicting_evidence.items()},
            "feature_snapshot_timestamp": self.feature_snapshot_timestamp,
            "data_quality": round(self.data_quality, 4),
            "status": self.status.value if isinstance(self.status, Enum) else str(self.status),
            "rejection_reason": self.rejection_reason.value if isinstance(self.rejection_reason, Enum) else (str(self.rejection_reason) if self.rejection_reason else None),
            "tier": self.tier.value if isinstance(self.tier, Enum) else str(self.tier),
            "created_at": self.created_at,
            "expires_at": self.expires_at,
            "source_candle_timestamp": self.source_candle_timestamp,
        }

    @staticmethod
    def create_id(symbol: str, strategy: str, timeframe: str, timestamp: float) -> str:
        return f"sig_{symbol}_{strategy}_{timeframe}_{int(timestamp)}_{uuid.uuid4().hex[:6]}"
