"""
Signal Bus for Deriv Crypto AI Bot Stage 4.

Provides thread-safe in-memory storage for StrategySignal objects, signal deduplication,
signal expiration handling, and query APIs for Stage 5 consensus engine consumption.
"""

from collections import deque
import logging
import threading
import time
from typing import Dict, List, Optional, Tuple

from src.strategy.signal import StrategySignal, SignalStatus

logger = logging.getLogger("SIGNAL_BUS")


class SignalBus:
    """
    Thread-safe Signal Bus holding recent StrategySignal evaluations.
    """

    def __init__(self, max_capacity: int = 1000, default_cooldown: float = 300.0):
        self.max_capacity = max_capacity
        self.default_cooldown = default_cooldown
        self._lock = threading.Lock()
        self._signals: deque = deque(maxlen=max_capacity)
        
        # Last candidate cache for deduplication: key -> StrategySignal
        # key format: (symbol, strategy, timeframe, direction)
        self._last_candidates: Dict[Tuple[str, str, str, str], StrategySignal] = {}

    def publish(self, signal: StrategySignal, deduplicate: bool = True) -> bool:
        """
        Publishes signal to bus. Applies deduplication rules for CANDIDATE signals.
        Returns True if signal was accepted and added to bus, False if suppressed as duplicate.
        """
        with self._lock:
            # 1. Clean expired signals periodically
            self._clean_expired_unlocked()

            # 2. Check deduplication for CANDIDATE signals
            if deduplicate and signal.is_candidate():
                key = (signal.symbol, signal.strategy, signal.timeframe, str(signal.direction))
                last_sig = self._last_candidates.get(key)
                
                if last_sig is not None:
                    # Check cooldown
                    time_diff = signal.timestamp - last_sig.timestamp
                    conf_diff = abs(signal.confidence - last_sig.confidence)
                    
                    # Suppress duplicate candidate if within cooldown and confidence delta is small (< 0.05)
                    if time_diff < self.default_cooldown and conf_diff < 0.05:
                        logger.debug(f"[SIGNAL_BUS] Suppressed duplicate signal for {key}")
                        return False

                # Update candidate cache
                self._last_candidates[key] = signal

            # 3. Add to signal store
            self._signals.append(signal)
            return True

    def _clean_expired_unlocked(self, current_time: Optional[float] = None):
        """Internal helper to mark expired candidates (caller must hold lock)."""
        now = time.time() if current_time is None else current_time
        for sig in self._signals:
            if sig.is_candidate() and sig.is_expired(now):
                sig.status = SignalStatus.ABSTAINED

    def clean_expired(self, current_time: Optional[float] = None):
        """Public thread-safe call to clean expired signals."""
        with self._lock:
            self._clean_expired_unlocked(current_time)

    def signals_for_symbol(self, symbol: str) -> List[StrategySignal]:
        """Returns all recorded signals for a specific symbol."""
        with self._lock:
            return [s for s in self._signals if s.symbol == symbol]

    def signals_for_strategy(self, strategy_name: str) -> List[StrategySignal]:
        """Returns all recorded signals generated by a specific strategy."""
        with self._lock:
            return [s for s in self._signals if s.strategy == strategy_name]

    def recent_candidates(self, limit: int = 50) -> List[StrategySignal]:
        """Returns recent active CANDIDATE signals."""
        with self._lock:
            self._clean_expired_unlocked()
            candidates = [s for s in self._signals if s.is_candidate()]
            return list(reversed(candidates))[:limit]

    def recent_rejections(self, limit: int = 50) -> List[StrategySignal]:
        """Returns recent REJECTED signals."""
        with self._lock:
            rejections = [s for s in self._signals if s.status == SignalStatus.REJECTED]
            return list(reversed(rejections))[:limit]

    def recent_abstentions(self, limit: int = 50) -> List[StrategySignal]:
        """Returns recent ABSTAINED signals."""
        with self._lock:
            abstentions = [s for s in self._signals if s.status == SignalStatus.ABSTAINED]
            return list(reversed(abstentions))[:limit]

    def clear(self):
        """Clears all signals from bus."""
        with self._lock:
            self._signals.clear()
            self._last_candidates.clear()

    def __len__(self) -> int:
        with self._lock:
            return len(self._signals)
